apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    test.app: "hello-world"
spec:
  containers:
  - name: nginx
    image: docker.io/nginx:1.14.2  # Update image with docker.io registry
    ports:
    - containerPort: 80
